export const SETTINGS_KEYS = {
  mobilePushCompat: 'mobile.push.enabled',
  notificationsPushEnabled: 'notifications.push.enabled',
  notificationsEmailEnabled: 'notifications.email.enabled',
  notificationsInAppEnabled: 'notifications.inApp.enabled',
  emailEnabled: 'email.enabled',
  smtpProvider: 'smtp.provider',
  smtpHost: 'smtp.host',
  smtpPort: 'smtp.port',
  smtpSecure: 'smtp.secure',
  smtpRequireTLS: 'smtp.requireTLS',
  smtpUser: 'smtp.user',
  smtpPass: 'smtp.pass',
  smtpFromName: 'smtp.fromName',
  smtpFromAddress: 'smtp.fromAddress',
  smtpReplyTo: 'smtp.replyTo',
  uploadsMaxPhotoSizeMb: 'uploads.maxPhotoSizeMb',
  uploadsAllowedPhotoMimeTypes: 'uploads.allowedPhotoMimeTypes',
  uploadsMaxDocumentSizeMb: 'uploads.maxDocumentSizeMb',
  uploadsAllowedDocumentMimeTypes: 'uploads.allowedDocumentMimeTypes',
} as const;
