services:
  backend:
    container_name: sim-tracker-backend
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
    networks:
      - web
    volumes:
      - /mnt/shared-app-files/sim-cards-codex:/usr/app/uploads
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.simtracker-backend.entrypoints=websecure'
      - 'traefik.http.routers.simtracker-backend.rule=Host(`sim-tracker.hopto.org`) && PathPrefix(`/backend`)'
      - 'traefik.http.routers.simtracker-backend.tls=true'
      - 'traefik.http.routers.simtracker-backend.tls.certresolver=le'
      - 'traefik.http.services.simtracker-backend.loadbalancer.server.port=3003'
      - 'traefik.http.middlewares.simtracker-backend-stripbackend.stripprefix.prefixes=/backend'
      - 'traefik.http.routers.simtracker-backend.middlewares=simtracker-backend-stripbackend'

  frontend:
    container_name: sim-tracker-frontend
    build:
      context: ./frontend
    restart: unless-stopped
    networks:
      - web
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.simtracker-frontend.entrypoints=websecure'
      - 'traefik.http.routers.simtracker-frontend.rule=Host(`sim-tracker.hopto.org`)'
      - 'traefik.http.routers.simtracker-frontend.tls=true'
      - 'traefik.http.routers.simtracker-frontend.tls.certresolver=le'
      - 'traefik.http.services.simtracker-frontend.loadbalancer.server.port=3004'

networks:
  web:
    external: true
